apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: gcr.io/qwiklabs-gcp-00-459904d6b8d8/client:latest
        env:
        - name: ACCOUNT_MANAGER_SERVICE_HOST
          value: "account-manager-service"
        - name: ACCOUNT_MANAGER_SERVICE_PORT
          value: "80"
        ports:
        - containerPort: 8080
