# FROM golang:1.16

# WORKDIR /app
# COPY . .

# RUN go mod init client && go build -o client

# CMD ["./client"]

# Use the official Golang image as the base image for the build stage
FROM golang:1.20 as builder

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the source code into the container
COPY . .

# Build the Go app
RUN go build -o client

# Use a minimal base image for the final stage
FROM gcr.io/distroless/base-debian10

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the binary from the builder stage
COPY --from=builder /app/client .

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the executable
CMD ["./client"]

