apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-manager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-manager
  template:
    metadata:
      labels:
        app: account-manager
    spec:
      containers:
      - name: account-manager
        image: gcr.io/consoleapp-1538806480615/account-manager:latest
        ports:
        - containerPort: 8080
