
# Use the official Golang image as the base image for the build stage
FROM golang:1.20

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the source code into the container
COPY go.mod .
copy account-manager.go .
# copy ../account-data.txt /app/account-data.txt

# Build the Go app
RUN go build -o account-manager

# Copy the source code into the container
COPY . .

# Set the environment variable for the service account key
ENV GOOGLE_APPLICATION_CREDENTIALS="/app/service-account-file.json"

# Copy the service account key into the container
COPY ../service-account-file.json /app/service-account-file.json


# Create the storage directory
# RUN mkdir -p /app/storage
# RUN touch account-data.txt

# Command to run the executable
ENTRYPOINT ["/app/account-manager"]

