# Clients and the account manager run in the same pod and communicate internally.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-system
  template:
    metadata:
      labels:
        app: account-system
    spec:
      containers:
      - name: client1
        image: gcr.io/PROJECT_ID/client:latest
        ports:
        - containerPort: 8080
        env:
        - name: CLIENT_ID
          value: client1  # Unique identifier for client1
      - name: client2
        image: gcr.io/PROJECT_ID/client:latest
        ports:
        - containerPort: 8081
        env:
        - name: CLIENT_ID
          value: client2  # Unique identifier for client2
      - name: account-manager
        image: gcr.io/PROJECT_ID/account-manager:latest
        ports:
        - containerPort: 8082
        volumeMounts:
        - name: storage-volume
          mountPath: /app/data
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: account-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: account-system
spec:
  selector:
    app: account-system
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082  # the account manager listens on port 8082
