apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-system
  template:
    metadata:
      labels:
        app: account-system
    spec:
      containers:
      - name: client1
        image: gcr.io/PROJECT_ID/client:latest
      - name: client2
        image: gcr.io/PROJECT_ID/client:latest
      - name: account-manager
        image: gcr.io/PROJECT_ID/account-manager:latest
        ports:
        - containerPort: 8080
      - name: accounts-monitor
        image: gcr.io/PROJECT_ID/accounts-monitor:latest
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: account-manager-service
spec:
  selector:
    app: account-system
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: accounts-monitor-service
spec:
  selector:
    app: account-system
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
