apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: account-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeMode: Filesystem
